# Generated by Django 4.1.5 on 2024-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('year_started', models.DateField()),
                ('year_completed', models.DateField()),
                ('role', models.TextField()),
            ],
            options={
                'ordering': ['year_completed'],
            },
        ),
    ]
