# Generated by Django 4.1.5 on 2024-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_skill_alter_experience_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_client', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('project_date', models.DateField()),
                ('project_url', models.CharField(max_length=100)),
                ('project_photos', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('project_details', models.TextField()),
            ],
            options={
                'ordering': ['project_date'],
            },
        ),
    ]
